name: skorch-deploy
channels:
  - pytorch
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - atomicwrites=1.2.1
  - attrs=18.2.0
  - blas=1.0=mkl
  - bleach=3.0.2
  - ca-certificates=2018.03.07
  - certifi=2018.10.15
  - cffi=1.11.5
  - chardet=3.0.4
  - cmarkgfm=0.4.2
  - coverage=4.5.1
  - cryptography=2.3.1
  - docutils=0.14
  - future=0.17.1
  - idna=2.7
  - intel-openmp=2019.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - mkl=2019.0
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - more-itertools=4.3.0
  - ncurses=6.1
  - ninja=1.8.2
  - numpy=1.15.3
  - numpy-base=1.15.3
  - openssl=1.1.1
  - pip=10.0.1
  - pkginfo=1.4.2
  - pluggy=0.8.0
  - py=1.7.0
  - pycparser=2.19
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pysocks=1.6.8
  - pytest=3.9.3
  - pytest-cov=2.6.0
  - python=3.6.7
  - readline=7.0
  - readme_renderer=24.0
  - requests=2.19.1
  - requests-toolbelt=0.8.0
  - scikit-learn=0.20.0
  - scipy=1.1.0
  - setuptools=40.5.0
  - six=1.11.0
  - sqlite=3.25.2
  - tk=8.6.8
  - tqdm=4.28.1
  - twine=1.12.1
  - urllib3=1.23
  - webencodings=0.5.1
  - wheel=0.32.2
  - xz=5.2.4
  - zlib=1.2.11
  - pytorch=0.4.1
  - pip:
    - flaky==3.4.0
    - tabulate==0.8.2
